// ============================================================
// PIXEL FACE STUDIO v2.0 - MAIN APPLICATION LOGIC
// ============================================================

// ------------------------------------------------------------
// 1. PALETTE & THEME CONFIGURATIONS
// ------------------------------------------------------------
const PALETTES = {
  cyberpunk: {
    bg: '#0a0a10',
    skin: '#1a1c2e',
    skinBorder: '#00f0ff',
    eye: '#ff0055',
    eyeGlow: '#ff0055',
    mouth: '#00f0ff',
    acc: '#ffe600',
    grid: 'rgba(0, 240, 255, 0.15)'
  },
  gameboy: {
    bg: '#0f380f',
    skin: '#8bac0f',
    skinBorder: '#306230',
    eye: '#0f380f',
    eyeGlow: '#9bbc0f',
    mouth: '#0f380f',
    acc: '#9bbc0f',
    grid: 'rgba(139, 172, 15, 0.2)'
  },
  'crt-amber': {
    bg: '#120a00',
    skin: '#331c00',
    skinBorder: '#ffb000',
    eye: '#ffb000',
    eyeGlow: '#ffb000',
    mouth: '#ff5500',
    acc: '#ffe600',
    grid: 'rgba(255, 176, 0, 0.2)'
  },
  synthwave: {
    bg: '#120426',
    skin: '#28124d',
    skinBorder: '#f72585',
    eye: '#4cc9f0',
    eyeGlow: '#4cc9f0',
    mouth: '#f72585',
    acc: '#ff7b00',
    grid: 'rgba(247, 37, 133, 0.2)'
  },
  pastel: {
    bg: '#141221',
    skin: '#2a2640',
    skinBorder: '#ffc6ff',
    eye: '#a0c4ff',
    eyeGlow: '#a0c4ff',
    mouth: '#ffadad',
    acc: '#caffbf',
    grid: 'rgba(255, 198, 255, 0.2)'
  },
  monochrome: {
    bg: '#000000',
    skin: '#222222',
    skinBorder: '#ffffff',
    eye: '#ffffff',
    eyeGlow: '#ffffff',
    mouth: '#ffffff',
    acc: '#888888',
    grid: 'rgba(255, 255, 255, 0.2)'
  }
};

// ------------------------------------------------------------
// 2. DEFAULT PIXEL ART GRID TEMPLATES (24x24 Grid)
// ------------------------------------------------------------
const GRID_SIZE = 24;

// Helper to create empty 24x24 matrix
function createEmptyGrid() {
  return Array(GRID_SIZE).fill(null).map(() => Array(GRID_SIZE).fill(0));
}

// Convert ASCII pattern string to 24x24 grid
function parsePattern(asciiStr, charMap) {
  const grid = createEmptyGrid();
  const lines = asciiStr.trim().split('\n').map(l => l.trim());
  for (let r = 0; r < Math.min(lines.length, GRID_SIZE); r++) {
    for (let c = 0; c < Math.min(lines[r].length, GRID_SIZE); c++) {
      const char = lines[r][c];
      grid[r][c] = charMap[char] || 0;
    }
  }
  return grid;
}

// ------------------------------------------------------------
// 3. PRESET CHARACTERS & PARTS
// ------------------------------------------------------------
// 1 = skinBorder, 2 = skinFill, 3 = eye, 4 = mouth, 5 = acc, 6 = highlight

// Default Face Shape (Base)
const BASE_CYBER = `
........................
......111111111111......
....1122222222222211....
...122222222222222221...
..12222222222222222221..
..12222222222222222221..
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
.1222222222222222222221.
..12222222222222222221..
..12222222222222222221..
...122222222222222221...
....1122222222222211....
......111111111111......
........................
........................
........................
........................
`;

// Eyes Variations
const EYES_NORMAL = `
........................
........................
........................
........................
........................
........................
........................
....3333........3333....
....3633........3633....
....3333........3333....
....3333........3333....
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_BLINK = `
........................
........................
........................
........................
........................
........................
........................
........................
....3333........3333....
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_SMILE = `
........................
........................
........................
........................
........................
........................
........................
....3..3........3..3....
...33..33......33..33...
....3333........3333....
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_SURPRISED = `
........................
........................
........................
........................
........................
........................
...333333......333333...
...336633......336633...
...336633......336633...
...333333......333333...
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_WINK = `
........................
........................
........................
........................
........................
........................
........................
....3333........3..3....
....3633.......33..33...
....3333........3333....
....3333................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_ANGRY = `
........................
........................
........................
........................
........................
...3...............3....
....33...........33.....
.....3333.....3333......
....3633........3633....
....3333........3333....
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_SLEEP = `
........................
........................
........................
........................
........................
........................
........................
........................
...333333......333333...
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const EYES_COOL = `
........................
........................
........................
........................
........................
...555555555555555555...
..55555555555555555555..
..55655555555556555555..
..55555555555555555555..
...5555555......555555..
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

// Mouth Variations (Closed, A, I, U, E, O)
const MOUTH_CLOSED = `
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
.......444444444........
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const MOUTH_A = `
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........4444444.........
.......444444444........
.......444444444........
........4444444.........
........................
........................
........................
........................
........................
........................
........................
........................
`;

const MOUTH_I = `
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
......444444444444......
......444444444444......
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const MOUTH_U = `
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
.........44444..........
.........44444..........
.........44444..........
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const MOUTH_E = `
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
.......444444444........
.......444444444........
........4444444.........
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const MOUTH_O = `
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........4444444.........
.......444444444........
.......444444444........
.......444444444........
........4444444.........
........................
........................
........................
........................
........................
........................
........................
`;

// Accessory Templates
const ACC_NONE = createEmptyGrid();

const ACC_HEADPHONES = `
....5555555555555555....
...55..............55...
..55................55..
..55................55..
.55..................55.
.55..................55.
.55..................55.
.5555..............5555.
.5555..............5555.
.5555..............5555.
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const ACC_CATEARS = `
..555............555....
..5655..........5565....
..56655........55665....
..55665........56655....
...5555........5555.....
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const ACC_CROWN = `
........5..5..5.........
.......55.55.55.........
......5555555555........
......5565556555........
......5555555555........
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const ACC_RIBBON = `
........55....55........
.......5555..5555.......
........55555555........
.........556655.........
..........5555..........
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;

const CHAR_MAP = {
  '.': 0,
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6
};

// Preset Avatars Configuration
const PRESETS = [
  { id: 'cyber', name: 'Cyber Boy', icon: '🤖', acc: ACC_HEADPHONES },
  { id: 'girl', name: 'Retro Girl', icon: '👧', acc: ACC_RIBBON },
  { id: 'cat', name: 'Cat Bot', icon: '🐱', acc: ACC_CATEARS },
  { id: 'slime', name: 'Slime', icon: '💧', acc: ACC_NONE },
  { id: 'wizard', name: 'Mage', icon: '🧙', acc: ACC_CROWN },
  { id: 'robo', name: '8-Bit Robo', icon: '👾', acc: ACC_HEADPHONES }
];

// ------------------------------------------------------------
// 4. APPLICATION STATE
// ------------------------------------------------------------
const state = {
  // Current Character & Layers
  paletteName: 'cyberpunk',
  currentPreset: 'cyber',
  currentExpression: 'neutral',
  currentAccessory: 'headphones',
  
  // Grid Data Matrices
  baseGrid: parsePattern(BASE_CYBER, CHAR_MAP),
  eyesGrid: parsePattern(EYES_NORMAL, CHAR_MAP),
  mouthClosedGrid: parsePattern(MOUTH_CLOSED, CHAR_MAP),
  mouthOpenGrid: parsePattern(MOUTH_A, CHAR_MAP),
  accGrid: parsePattern(ACC_HEADPHONES, CHAR_MAP),

  // Dynamic Mouth / Audio State
  mouthState: 'closed', // 'closed', 'A', 'I', 'U', 'E', 'O'
  mouthOpenness: 0, // 0 to 1
  isDemoTalking: false,

  // Blink Engine State
  isBlinking: false,
  blinkTimer: null,
  nextBlinkDelay: 3000,

  // Audio Engine State
  audioCtx: null,
  analyser: null,
  micStream: null,
  isMicActive: false,
  sensitivity: 2.5,
  threshold: 15, // %
  
  // Render Settings
  crtEnabled: true,
  glowEnabled: true,
  gridEnabled: false,
  bounceEnabled: true,
  bgMode: 'dark', // 'dark', 'green', 'blue', 'transparent'
  
  // Editor Modal State
  editorActivePart: 'base',
  editorTool: 'pen',
  editorColor: '#00f0ff',
  editorGrid: createEmptyGrid()
};

// ------------------------------------------------------------
// 5. CANVAS RENDER ENGINE
// ------------------------------------------------------------
let avatarCanvas, ctx;
let obsCanvas, obsCtx;
let lastTime = 0;
let bounceOffset = 0;

function initCanvas() {
  avatarCanvas = document.getElementById('avatar-canvas');
  ctx = avatarCanvas.getContext('2d');
  
  obsCanvas = document.getElementById('obs-avatar-canvas');
  obsCtx = obsCanvas.getContext('2d');

  // Disable smoothing for sharp pixels
  ctx.imageSmoothingEnabled = false;
  obsCtx.imageSmoothingEnabled = false;

  requestAnimationFrame(renderLoop);
}

function renderLoop(time) {
  const dt = time - lastTime;
  lastTime = time;

  // Bounce animation calculation
  if (state.bounceEnabled) {
    bounceOffset = Math.sin(time * 0.003) * 6;
  } else {
    bounceOffset = 0;
  }

  // Demo Talking Loop
  if (state.isDemoTalking) {
    const talkCycle = (time % 600) / 600;
    if (talkCycle < 0.2) state.mouthState = 'closed';
    else if (talkCycle < 0.4) state.mouthState = 'A';
    else if (talkCycle < 0.6) state.mouthState = 'I';
    else if (talkCycle < 0.8) state.mouthState = 'O';
    else state.mouthState = 'U';
  }

  // Draw Avatar onto main canvas & OBS canvas
  drawAvatar(ctx, avatarCanvas.width, avatarCanvas.height);
  drawAvatar(obsCtx, obsCanvas.width, obsCanvas.height);

  requestAnimationFrame(renderLoop);
}

function drawAvatar(c, width, height) {
  c.clearRect(0, 0, width, height);

  // Background Mode
  if (state.bgMode === 'green') {
    c.fillStyle = '#00ff00';
    c.fillRect(0, 0, width, height);
  } else if (state.bgMode === 'blue') {
    c.fillStyle = '#0000ff';
    c.fillRect(0, 0, width, height);
  } else if (state.bgMode === 'dark') {
    c.fillStyle = PALETTES[state.paletteName].bg;
    c.fillRect(0, 0, width, height);
  } // transparent does nothing

  const pixelSize = Math.floor(width / GRID_SIZE);
  const startX = 0;
  const startY = Math.round(bounceOffset);

  const palette = PALETTES[state.paletteName];

  // Helper to resolve pixel color code to RGB hex
  function getColor(code) {
    switch (code) {
      case 1: return palette.skinBorder;
      case 2: return palette.skin;
      case 3: return palette.eye;
      case 4: return palette.mouth;
      case 5: return palette.acc;
      case 6: return '#ffffff';
      default:
        // Handle hex string if edited by pixel editor
        if (typeof code === 'string' && code.startsWith('#')) return code;
        return null;
    }
  }

  // Render Grid Layers
  const layers = [
    state.baseGrid,
    getEyeGridForCurrentState(),
    getMouthGridForCurrentState(),
    state.accGrid
  ];

  c.save();

  // Glow Effect
  if (state.glowEnabled) {
    c.shadowColor = palette.eyeGlow;
    c.shadowBlur = 12;
  }

  for (let r = 0; r < GRID_SIZE; r++) {
    for (let col = 0; col < GRID_SIZE; col++) {
      for (const layer of layers) {
        if (!layer) continue;
        const val = layer[r][col];
        if (val !== 0) {
          const color = getColor(val);
          if (color) {
            c.fillStyle = color;
            c.fillRect(
              startX + col * pixelSize, 
              startY + r * pixelSize, 
              pixelSize, 
              pixelSize
            );
          }
        }
      }
    }
  }

  c.restore();

  // Optional Dot Grid Lines
  if (state.gridEnabled) {
    c.strokeStyle = palette.grid;
    c.lineWidth = 1;
    for (let i = 0; i <= GRID_SIZE; i++) {
      c.beginPath();
      c.moveTo(i * pixelSize, 0);
      c.lineTo(i * pixelSize, height);
      c.stroke();

      c.beginPath();
      c.moveTo(0, i * pixelSize);
      c.lineTo(width, i * pixelSize);
      c.stroke();
    }
  }
}

// ------------------------------------------------------------
// 6. EXPRESSION & BLINK RESOLUTION
// ------------------------------------------------------------
function getEyeGridForCurrentState() {
  if (state.isBlinking) {
    return parsePattern(EYES_BLINK, CHAR_MAP);
  }

  switch (state.currentExpression) {
    case 'smile': return parsePattern(EYES_SMILE, CHAR_MAP);
    case 'surprised': return parsePattern(EYES_SURPRISED, CHAR_MAP);
    case 'wink': return parsePattern(EYES_WINK, CHAR_MAP);
    case 'angry': return parsePattern(EYES_ANGRY, CHAR_MAP);
    case 'sad': return parsePattern(EYES_ANGRY, CHAR_MAP);
    case 'sleep': return parsePattern(EYES_SLEEP, CHAR_MAP);
    case 'cool': return parsePattern(EYES_COOL, CHAR_MAP);
    case 'neutral':
    default:
      return state.eyesGrid || parsePattern(EYES_NORMAL, CHAR_MAP);
  }
}

function getMouthGridForCurrentState() {
  switch (state.mouthState) {
    case 'A': return parsePattern(MOUTH_A, CHAR_MAP);
    case 'I': return parsePattern(MOUTH_I, CHAR_MAP);
    case 'U': return parsePattern(MOUTH_U, CHAR_MAP);
    case 'E': return parsePattern(MOUTH_E, CHAR_MAP);
    case 'O': return parsePattern(MOUTH_O, CHAR_MAP);
    case 'closed':
    default:
      return state.mouthClosedGrid || parsePattern(MOUTH_CLOSED, CHAR_MAP);
  }
}

// Automatic Random Blinking Engine
function startBlinkEngine() {
  function triggerBlink() {
    state.isBlinking = true;
    setTimeout(() => {
      state.isBlinking = false;
      const delay = Math.random() * 3000 + 2000;
      setTimeout(triggerBlink, delay);
    }, 120);
  }

  setTimeout(triggerBlink, 3000);
}

// ------------------------------------------------------------
// 7. MICROPHONE AUDIO ANALYZER (LIP-SYNC)
// ------------------------------------------------------------
async function toggleMicrophone() {
  const btn = document.getElementById('btn-toggle-mic');
  const hudStatus = document.getElementById('hud-status');

  if (state.isMicActive) {
    // Stop Microphone
    if (state.micStream) {
      state.micStream.getTracks().forEach(track => track.stop());
    }
    state.isMicActive = false;
    btn.innerHTML = '<span class="mic-icon">🎙️</span> マイクを開始';
    btn.classList.remove('btn-primary');
    btn.classList.add('btn-primary');
    hudStatus.textContent = 'マイク: 停止中';
    state.mouthState = 'closed';
    return;
  }

  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    state.micStream = stream;
    state.audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    const source = state.audioCtx.createMediaStreamSource(stream);
    
    state.analyser = state.audioCtx.createAnalyser();
    state.analyser.fftSize = 512;
    source.connect(state.analyser);

    state.isMicActive = true;
    btn.innerHTML = '<span class="mic-icon">🛑</span> マイクを停止';
    btn.classList.remove('btn-primary');
    btn.classList.add('btn-danger');
    hudStatus.textContent = 'マイク: 動作中';

    processAudio();

  } catch (err) {
    alert('マイクの取得に失敗しました。マイクのアクセス許可を確認してください。');
    console.error(err);
  }
}

function processAudio() {
  if (!state.isMicActive || !state.analyser) return;

  const dataArray = new Uint8Array(state.analyser.frequencyBinCount);
  state.analyser.getByteFrequencyData(dataArray);

  // Calculate Volume (RMS)
  let sum = 0;
  for (let i = 0; i < dataArray.length; i++) {
    sum += dataArray[i] * dataArray[i];
  }
  const rms = Math.sqrt(sum / dataArray.length);
  const rawVolPercent = Math.min(100, Math.round((rms / 128) * 100 * state.sensitivity));

  // Update Meter UI
  const volBar = document.getElementById('vol-bar');
  const volVal = document.getElementById('vol-value');
  volBar.style.width = `${rawVolPercent}%`;
  volVal.textContent = `${rawVolPercent}%`;

  // Check Silence Threshold
  if (rawVolPercent < state.threshold) {
    state.mouthState = 'closed';
    updateVowelsUI('closed');
  } else {
    // Frequency spectral analysis for Japanese Vowel Detection
    // Low: 100-500Hz, Mid: 500-1500Hz, High: 1500-4000Hz
    const lowEnergy = getEnergyRange(dataArray, 2, 10);
    const midEnergy = getEnergyRange(dataArray, 10, 30);
    const highEnergy = getEnergyRange(dataArray, 30, 80);

    let detectedVowel = 'A';

    if (highEnergy > midEnergy && highEnergy > lowEnergy) {
      detectedVowel = 'I'; // 'い' (High frequency emphasis)
    } else if (lowEnergy > midEnergy * 1.3) {
      detectedVowel = 'U'; // 'う' (Deep low frequency)
    } else if (midEnergy > lowEnergy && midEnergy > highEnergy) {
      detectedVowel = 'O'; // 'お' (Mid range emphasis)
    } else if (rawVolPercent > 50) {
      detectedVowel = 'A'; // 'あ' (Wide open)
    } else {
      detectedVowel = 'E'; // 'え'
    }

    state.mouthState = detectedVowel;
    updateVowelsUI(detectedVowel);
  }

  requestAnimationFrame(processAudio);
}

function getEnergyRange(array, startBin, endBin) {
  let total = 0;
  for (let i = startBin; i < endBin && i < array.length; i++) {
    total += array[i];
  }
  return total / (endBin - startBin);
}

function updateVowelsUI(activeVowel) {
  const vowels = ['a', 'i', 'u', 'e', 'o'];
  vowels.forEach(v => {
    const el = document.getElementById(`vowel-${v}`);
    if (v.toUpperCase() === activeVowel) {
      el.classList.add('active');
    } else {
      el.classList.remove('active');
    }
  });
}

// ------------------------------------------------------------
// 8. PIXEL ART EDITOR LOGIC
// ------------------------------------------------------------
let editorCanvas, editorCtx;
let isDrawingInEditor = false;

function initPixelEditor() {
  editorCanvas = document.getElementById('editor-canvas');
  editorCtx = editorCanvas.getContext('2d');
  editorCtx.imageSmoothingEnabled = false;

  // Render Palette Dot Controls
  const quickPalette = document.getElementById('quick-palette');
  const colors = ['#00f0ff', '#ff0055', '#ffe600', '#00ff66', '#ffffff', '#000000', '#1a1c2e', '#f72585', '#a0c4ff', '#8bac0f'];
  
  colors.forEach(c => {
    const dot = document.createElement('div');
    dot.className = 'color-dot';
    dot.style.background = c;
    dot.addEventListener('click', () => {
      document.getElementById('editor-color-picker').value = c;
      state.editorColor = c;
    });
    quickPalette.appendChild(dot);
  });

  // Editor Mouse Listeners
  editorCanvas.addEventListener('mousedown', handleEditorPointerDown);
  editorCanvas.addEventListener('mousemove', handleEditorPointerMove);
  window.addEventListener('mouseup', () => { isDrawingInEditor = false; });
}

function openEditorModal() {
  document.getElementById('editor-modal').classList.remove('hidden');
  loadPartToEditor();
}

function loadPartToEditor() {
  const part = document.getElementById('editor-part-select').value;
  state.editorActivePart = part;

  let sourceGrid;
  switch (part) {
    case 'base': sourceGrid = state.baseGrid; break;
    case 'eyes': sourceGrid = state.eyesGrid; break;
    case 'mouthOpen': sourceGrid = state.mouthOpenGrid; break;
    case 'mouthClosed': sourceGrid = state.mouthClosedGrid; break;
    case 'accessory': sourceGrid = state.accGrid; break;
    default: sourceGrid = createEmptyGrid();
  }

  // Clone to editor grid
  state.editorGrid = sourceGrid.map(row => [...row]);
  drawEditorCanvas();
}

function drawEditorCanvas() {
  const size = editorCanvas.width / GRID_SIZE;
  editorCtx.clearRect(0, 0, editorCanvas.width, editorCanvas.height);

  const palette = PALETTES[state.paletteName];

  for (let r = 0; r < GRID_SIZE; r++) {
    for (let c = 0; c < GRID_SIZE; c++) {
      const val = state.editorGrid[r][c];
      if (val !== 0) {
        if (typeof val === 'string') {
          editorCtx.fillStyle = val;
        } else {
          switch (val) {
            case 1: editorCtx.fillStyle = palette.skinBorder; break;
            case 2: editorCtx.fillStyle = palette.skin; break;
            case 3: editorCtx.fillStyle = palette.eye; break;
            case 4: editorCtx.fillStyle = palette.mouth; break;
            case 5: editorCtx.fillStyle = palette.acc; break;
            default: editorCtx.fillStyle = '#ffffff';
          }
        }
        editorCtx.fillRect(c * size, r * size, size, size);
      }
    }
  }

  // Grid Lines in Editor
  editorCtx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
  for (let i = 0; i <= GRID_SIZE; i++) {
    editorCtx.beginPath();
    editorCtx.moveTo(i * size, 0);
    editorCtx.lineTo(i * size, editorCanvas.height);
    editorCtx.stroke();

    editorCtx.beginPath();
    editorCtx.moveTo(0, i * size);
    editorCtx.lineTo(editorCanvas.width, i * size);
    editorCtx.stroke();
  }
}

function handleEditorPointerDown(e) {
  isDrawingInEditor = true;
  paintPixelAtPointer(e);
}

function handleEditorPointerMove(e) {
  if (isDrawingInEditor) {
    paintPixelAtPointer(e);
  }
}

function paintPixelAtPointer(e) {
  const rect = editorCanvas.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const y = e.clientY - rect.top;
  
  const col = Math.floor((x / rect.width) * GRID_SIZE);
  const row = Math.floor((y / rect.height) * GRID_SIZE);

  if (row >= 0 && row < GRID_SIZE && col >= 0 && col < GRID_SIZE) {
    if (state.editorTool === 'pen') {
      state.editorGrid[row][col] = state.editorColor;
    } else if (state.editorTool === 'eraser') {
      state.editorGrid[row][col] = 0;
    }
    drawEditorCanvas();
  }
}

function applyEditorChanges() {
  const part = state.editorActivePart;
  const newGrid = state.editorGrid.map(row => [...row]);

  switch (part) {
    case 'base': state.baseGrid = newGrid; break;
    case 'eyes': state.eyesGrid = newGrid; break;
    case 'mouthOpen': state.mouthOpenGrid = newGrid; break;
    case 'mouthClosed': state.mouthClosedGrid = newGrid; break;
    case 'accessory': state.accGrid = newGrid; break;
  }

  document.getElementById('editor-modal').classList.add('hidden');
}

// ------------------------------------------------------------
// 9. UI EVENT LISTENERS & INITIALIZATION
// ------------------------------------------------------------
function initUI() {
  // Preset Buttons
  const presetContainer = document.getElementById('preset-grid');
  PRESETS.forEach(p => {
    const btn = document.createElement('button');
    btn.className = `btn-preset ${p.id === state.currentPreset ? 'active' : ''}`;
    btn.innerHTML = `<span class="preset-icon">${p.icon}</span><span class="preset-name">${p.name}</span>`;
    btn.addEventListener('click', () => {
      document.querySelectorAll('.btn-preset').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.currentPreset = p.id;
      state.accGrid = p.acc;
    });
    presetContainer.appendChild(btn);
  });

  // Accessories Buttons
  const accContainer = document.getElementById('accessory-grid');
  const accs = [
    { icon: '🚫', acc: ACC_NONE },
    { icon: '🎧', acc: parsePattern(ACC_HEADPHONES, CHAR_MAP) },
    { icon: '🐱', acc: parsePattern(ACC_CATEARS, CHAR_MAP) },
    { icon: '👑', acc: parsePattern(ACC_CROWN, CHAR_MAP) },
    { icon: '🎀', acc: parsePattern(ACC_RIBBON, CHAR_MAP) }
  ];
  accs.forEach((a, i) => {
    const btn = document.createElement('button');
    btn.className = `btn-acc ${i === 1 ? 'active' : ''}`;
    btn.innerHTML = a.icon;
    btn.addEventListener('click', () => {
      document.querySelectorAll('.btn-acc').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.accGrid = a.acc;
    });
    accContainer.appendChild(btn);
  });

  // Expression Buttons
  document.querySelectorAll('.btn-exp').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.btn-exp').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.currentExpression = btn.dataset.exp;
    });
  });

  // Palette Buttons
  document.querySelectorAll('.palette-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.palette-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.paletteName = btn.dataset.theme;
      document.body.className = `theme-${state.paletteName}`;
    });
  });

  // Toggles
  document.getElementById('toggle-crt').addEventListener('change', e => {
    document.getElementById('crt-overlay').style.display = e.target.checked ? 'block' : 'none';
  });
  document.getElementById('toggle-glow').addEventListener('change', e => {
    state.glowEnabled = e.target.checked;
  });
  document.getElementById('toggle-grid').addEventListener('change', e => {
    state.gridEnabled = e.target.checked;
  });
  document.getElementById('toggle-bounce').addEventListener('change', e => {
    state.bounceEnabled = e.target.checked;
  });

  // Background Buttons
  document.querySelectorAll('.btn-bg-opt').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.btn-bg-opt').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.bgMode = btn.dataset.bg;
    });
  });

  // Mic & Sliders
  document.getElementById('btn-toggle-mic').addEventListener('click', toggleMicrophone);
  
  document.getElementById('slider-sens').addEventListener('input', e => {
    state.sensitivity = parseFloat(e.target.value);
    document.getElementById('val-sens').textContent = state.sensitivity;
  });

  document.getElementById('slider-thresh').addEventListener('input', e => {
    state.threshold = parseInt(e.target.value);
    document.getElementById('val-thresh').textContent = `${state.threshold}%`;
    document.getElementById('threshold-line').style.left = `${state.threshold}%`;
  });

  document.getElementById('slider-manual-mouth').addEventListener('input', e => {
    const val = parseInt(e.target.value);
    document.getElementById('val-manual-mouth').textContent = `${val}%`;
    if (val === 0) {
      state.mouthState = 'closed';
    } else if (val < 25) {
      state.mouthState = 'E';
    } else if (val < 50) {
      state.mouthState = 'I';
    } else if (val < 75) {
      state.mouthState = 'O';
    } else {
      state.mouthState = 'A';
    }
  });

  document.getElementById('btn-demo-talk').addEventListener('click', () => {
    state.isDemoTalking = !state.isDemoTalking;
    const btn = document.getElementById('btn-demo-talk');
    btn.textContent = state.isDemoTalking ? '⏹ 自動トーク停止' : '▶ 自動トークテスト (ON/OFF)';
  });

  // OBS Clean Mode
  document.getElementById('btn-obs-mode').addEventListener('click', () => {
    document.getElementById('obs-clean-mode').classList.remove('hidden');
  });
  document.getElementById('obs-clean-mode').addEventListener('click', () => {
    document.getElementById('obs-clean-mode').classList.add('hidden');
  });
  window.addEventListener('keydown', e => {
    if (e.key === 'Escape') {
      document.getElementById('obs-clean-mode').classList.add('hidden');
      document.getElementById('editor-modal').classList.add('hidden');
    }
  });

  // Export PNG
  document.getElementById('btn-export-png').addEventListener('click', () => {
    const link = document.createElement('a');
    link.download = `pixel-face-${state.currentPreset}-${Date.now()}.png`;
    link.href = avatarCanvas.toDataURL('image/png');
    link.click();
  });

  // Editor Modal Events
  document.getElementById('btn-pixel-editor').addEventListener('click', openEditorModal);
  document.getElementById('btn-close-editor').addEventListener('click', () => {
    document.getElementById('editor-modal').classList.add('hidden');
  });
  document.getElementById('editor-part-select').addEventListener('change', loadPartToEditor);
  document.getElementById('editor-color-picker').addEventListener('input', e => {
    state.editorColor = e.target.value;
  });

  document.querySelectorAll('.btn-tool').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.btn-tool').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.editorTool = btn.dataset.tool;
    });
  });

  document.getElementById('btn-save-editor').addEventListener('click', applyEditorChanges);
  document.getElementById('btn-reset-part').addEventListener('click', () => {
    state.editorGrid = createEmptyGrid();
    drawEditorCanvas();
  });
}

// ------------------------------------------------------------
// 10. INITIALIZATION ENTRY POINT
// ------------------------------------------------------------
window.addEventListener('DOMContentLoaded', () => {
  initCanvas();
  initUI();
  initPixelEditor();
  startBlinkEngine();
});
